apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    stack: deck
  name: spin-deck-nodeport-service
  namespace: spinnaker
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: monitoring
    port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: spin
    cluster: spin-deck
  type: NodePort

